stages:
  - build
  - test
  - release

default:
  image: golang:1.19

test:
  stage: build
  script:
    - go test -json ./... 2>&1 | ./dev/linux/go-junit-report -parser gojson > junit.xml
  artifacts:
    reports:
      junit: junit.xml

build:
  stage: build
  variables:
    GOOS: linux
    GOARCH: amd64
  script:
    - CGO_ENABLED=0 go build -ldflags "-X main.version=$(git describe --tags --abbrev=0) -X main.revision=$(git rev-parse --short HEAD)" -o codequality-converter-linux main/main.go
  artifacts:
    name: dist
    paths:
      - ./codequality-converter-linux

test:convert:
  stage: test
  script:
    - ./codequality-converter-linux ./testing/fixture/semgrep.sarif gl-sast-report.json
    - diff ./testing/fixture/actual.json gl-sast-report.json > /dev/null
  artifacts:
    paths:
      - ./gl-sast-report.json
  needs: [build]

test:sast:
  image: $CI_TEMPLATE_REGISTRY_HOST/security-products/semgrep:3
  stage: test
  script:
    - /analyzer run
    - ./codequality-converter-linux semgrep.sarif gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
  needs: [build]

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  script: echo Release...
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: 'TODO: write release note.'
    assets:
      links:
        - name: codequality-converter-linux
          url: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/raw/codequality-converter-linux?job=release
          filepath: /bin/codequality-converter-linux
          link_type: other
  artifacts:
    name: codequality-converter
    paths:
      - codequality-converter-linux
    expire_in: never
  dependencies: [build]
  only:
    - tags
